package com.yumu.dto;

import java.util.Date;

public class MenuUrl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.menu_id
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.url
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.delete_flg
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    private Integer deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.create_user
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.create_datetime
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.update_user
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.update_datetime
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.menu_id
     *
     * @return the value of menu_url.menu_id
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.menu_id
     *
     * @param menuId the value for menu_url.menu_id
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.url
     *
     * @return the value of menu_url.url
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.url
     *
     * @param url the value for menu_url.url
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.delete_flg
     *
     * @return the value of menu_url.delete_flg
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public Integer getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.delete_flg
     *
     * @param deleteFlg the value for menu_url.delete_flg
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public void setDeleteFlg(Integer deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.create_user
     *
     * @return the value of menu_url.create_user
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.create_user
     *
     * @param createUser the value for menu_url.create_user
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.create_datetime
     *
     * @return the value of menu_url.create_datetime
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.create_datetime
     *
     * @param createDatetime the value for menu_url.create_datetime
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.update_user
     *
     * @return the value of menu_url.update_user
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.update_user
     *
     * @param updateUser the value for menu_url.update_user
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.update_datetime
     *
     * @return the value of menu_url.update_datetime
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.update_datetime
     *
     * @param updateDatetime the value for menu_url.update_datetime
     *
     * @mbg.generated Tue Sep 15 09:55:32 CST 2020
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}