package com.yumu.dto;

public class MenuUrlKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.menu_id
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.menu_id
     *
     * @return the value of menu_url.menu_id
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.menu_id
     *
     * @param menuId the value for menu_url.menu_id
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.url
     *
     * @return the value of menu_url.url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.url
     *
     * @param url the value for menu_url.url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }
}