package com.yumu.dto;

import java.util.Date;

public class MenuUrl extends MenuUrlKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.state
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.create_user
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.create_datetime
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.update_user
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_url.update_datetime
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.state
     *
     * @return the value of menu_url.state
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.state
     *
     * @param state the value for menu_url.state
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.create_user
     *
     * @return the value of menu_url.create_user
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.create_user
     *
     * @param createUser the value for menu_url.create_user
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.create_datetime
     *
     * @return the value of menu_url.create_datetime
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.create_datetime
     *
     * @param createDatetime the value for menu_url.create_datetime
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.update_user
     *
     * @return the value of menu_url.update_user
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.update_user
     *
     * @param updateUser the value for menu_url.update_user
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_url.update_datetime
     *
     * @return the value of menu_url.update_datetime
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_url.update_datetime
     *
     * @param updateDatetime the value for menu_url.update_datetime
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}