package com.yumu.dto;

import java.util.Date;

public class MenuInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_info.menu_id
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	private String menuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_info.title
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_info.url
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_info.parent_id
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	private String parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_info.level
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_info.hide_flg
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	private Integer hideFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_info.delete_flg
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	private Integer deleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_info.create_user
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_info.create_datetime
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	private Date createDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_info.update_user
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_info.update_datetime
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_info.menu_id
	 * @return  the value of menu_info.menu_id
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public String getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_info.menu_id
	 * @param menuId  the value for menu_info.menu_id
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_info.title
	 * @return  the value of menu_info.title
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_info.title
	 * @param title  the value for menu_info.title
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_info.url
	 * @return  the value of menu_info.url
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_info.url
	 * @param url  the value for menu_info.url
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_info.parent_id
	 * @return  the value of menu_info.parent_id
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_info.parent_id
	 * @param parentId  the value for menu_info.parent_id
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_info.level
	 * @return  the value of menu_info.level
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_info.level
	 * @param level  the value for menu_info.level
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_info.hide_flg
	 * @return  the value of menu_info.hide_flg
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public Integer getHideFlg() {
		return hideFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_info.hide_flg
	 * @param hideFlg  the value for menu_info.hide_flg
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public void setHideFlg(Integer hideFlg) {
		this.hideFlg = hideFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_info.delete_flg
	 * @return  the value of menu_info.delete_flg
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public Integer getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_info.delete_flg
	 * @param deleteFlg  the value for menu_info.delete_flg
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public void setDeleteFlg(Integer deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_info.create_user
	 * @return  the value of menu_info.create_user
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_info.create_user
	 * @param createUser  the value for menu_info.create_user
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_info.create_datetime
	 * @return  the value of menu_info.create_datetime
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public Date getCreateDatetime() {
		return createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_info.create_datetime
	 * @param createDatetime  the value for menu_info.create_datetime
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_info.update_user
	 * @return  the value of menu_info.update_user
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_info.update_user
	 * @param updateUser  the value for menu_info.update_user
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_info.update_datetime
	 * @return  the value of menu_info.update_datetime
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_info.update_datetime
	 * @param updateDatetime  the value for menu_info.update_datetime
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}
}