package com.yumu.dto;

import java.util.Date;

public class RoleMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.id
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.role_id
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.menu_id
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.state
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.create_user
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.create_datetime
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.update_user
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.update_datetime
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.id
     *
     * @return the value of role_menu.id
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.id
     *
     * @param id the value for role_menu.id
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.role_id
     *
     * @return the value of role_menu.role_id
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.role_id
     *
     * @param roleId the value for role_menu.role_id
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.menu_id
     *
     * @return the value of role_menu.menu_id
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.menu_id
     *
     * @param menuId the value for role_menu.menu_id
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.state
     *
     * @return the value of role_menu.state
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.state
     *
     * @param state the value for role_menu.state
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.create_user
     *
     * @return the value of role_menu.create_user
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.create_user
     *
     * @param createUser the value for role_menu.create_user
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.create_datetime
     *
     * @return the value of role_menu.create_datetime
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.create_datetime
     *
     * @param createDatetime the value for role_menu.create_datetime
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.update_user
     *
     * @return the value of role_menu.update_user
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.update_user
     *
     * @param updateUser the value for role_menu.update_user
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.update_datetime
     *
     * @return the value of role_menu.update_datetime
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.update_datetime
     *
     * @param updateDatetime the value for role_menu.update_datetime
     *
     * @mbg.generated Wed Nov 04 17:04:49 CST 2020
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}