package com.yumu.mapper;

import com.yumu.dto.MenuUrl;
import com.yumu.dto.MenuUrlExample;
import com.yumu.dto.MenuUrlKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    long countByExample(MenuUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    int deleteByExample(MenuUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    int deleteByPrimaryKey(MenuUrlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    int insert(MenuUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    int insertSelective(MenuUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    List<MenuUrl> selectByExample(MenuUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    MenuUrl selectByPrimaryKey(MenuUrlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") MenuUrl record, @Param("example") MenuUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    int updateByExample(@Param("record") MenuUrl record, @Param("example") MenuUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    int updateByPrimaryKeySelective(MenuUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_url
     *
     * @mbg.generated Tue Nov 03 08:40:35 CST 2020
     */
    int updateByPrimaryKey(MenuUrl record);
}