package com.yumu.mapper;

import com.yumu.controller.login.resp.MenuResp;
import com.yumu.dto.MenuInfo;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MenuInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu_info
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	int deleteByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu_info
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	int insert(MenuInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu_info
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	MenuInfo selectByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu_info
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	List<MenuInfo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu_info
	 * @mbg.generated  Tue Sep 15 09:54:26 CST 2020
	 */
	int updateByPrimaryKey(MenuInfo record);

	/* Local Method */
	/**
	 * <p>Title: qryMenuList</p>
	 * <p>Description:</p>
	 * @param userId
	 * @return
	 */
	List<MenuResp> qryMenuList(@Param("userId") String userId);

}